name: module3_task1
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  module3_task1_1:

    runs-on: ubuntu-18.04

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: running setup.sh
        run: |
          cd module3_task1/
          sudo ./setup.sh
      - name: Build
        run: |
          cd module3_task1
          make build
      - name: post
        env:
          POST_NAME: my-post
          POST_TITLE: My Post
        run: |
          cd module3_task1
          make post
      - name: yaml-lint
        run: |
          cd module3_task1
          make lint
      - name: clean
        run: |
          cd module3_task1
          make clean
