name: module3_task1
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - name: Executing the script setup.sh
    - uses: actions/checkout@v3
    - run: |
        cd module3_task1/
        sudo ./setup.sh
    - run: |
          cd module3_task0/
          make help
          make build
          make clean
          make build
          make post POST_NAME="name" POST_TITLE="title"
