name: module3_task1
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  module3_task1_1:

    runs-on: ubuntu-18.04

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: running setup.sh
        run: |
          cd module3_task1/
          sudo ./setup.sh
      - name: help
        run: |
          cd module3_task1
          make help
      - name: build1
        run: |
          cd module3_task1
          make build
      - name: clean
        run: |
          cd module3_task1
          make clean
      - name: build2
        run: |
          cd module3_task1
          make build
      - name: post
        env:
          POST_NAME: name
          POST_TITLE: title
        run: |
          cd module3_task1
          make post

