name: module3_task3
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
jobs:
  module3_task1_1:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: running setup.sh
        run: |
          cd module3_task2/
          sudo ./setup.sh
      - name: install markdown
        run: npm install -g markdownlint-cli
      - name: help
        run: |
          cd module3_task3
          make help
      - name: build1
        run: |
          cd module3_task3
          make build
      - name: clean
        run: |
          cd module3_task3
          make clean
      - name: build2
        run: |
          cd module3_task3
          make build
      - name: post
        env:
          POST_NAME: name
          POST_TITLE: title
        run: |
          cd module3_task3
          make post
      - name: lint
        run: |
          cd module3_task3
          make lint
      - name: package
        run: |
          cd module3_task3
          make package
      - name: unit-tests
        run: |
          cd module3_task3
          make unit-tests
      - name: integration-tests
        run: |
          cd module3_task3
          make integration-tests
      - name: validate
        run: |
          cd module3_task3
          make validate
      - name: release
          cd module3_task3
        run: npm install -g markdownlint-cli && make lint
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/1.0.0')
        with:
          files: |
            module3_task3/awesome-website.zip
            module3_task3/DEPLOY.md
          body_path: module3_task3/DEPLOY.md
