name: module3_task1
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
    
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Clone
        uses: actions/checkout@v3
      - name: install hugo
        run: |
          cd module3_task1/setup.sh 
      - name: help
        run: |
          cd module3_task1/
          make help
          make build
          make clean
          make build
          make post POST_NAME="name" POST_TITLE="title"
