name: module3_task1
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  module3_task1_1:

    runs-on: ubuntu-18.04

    steps:
    - name: Executing the script setup.sh
    - uses: actions/checkout@v3
    - run: |
        cd module3_task1/
        sudo ./setup.sh
    - run: |
        cd module3_task1/
        make help
    - run: |
        cd module3_task1/
        make build
    - run: |
        cd module3_task1/
        make clean
    - run: |
        cd module3_task1/
        make build
    - run: |
        cd module3_task1/
        make post POST_NAME="name" POST_TITLE="title"
