# This is a basic workflow that is manually triggered

name: module3_task0
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - main
        schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          cd module3_task0/
          make help
