
name: module3_task1
on:
  push:
    paths:
      - 'module3_task1/**'
  schedule:
    - cron: '0 0 * * *'

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Clone
        uses: actions/checkout@v3
      - name: install hugo
        run: |
          cd module3_task1 && ./setup.sh 
      - name: help
        run: |
          cd module3_task1/
          make build
