# This is a basic workflow that is manually triggered

name: module3_task0
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: '14'
      - run: cd module3_task0/
      - run: make help
