name: module3_task2
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'


jobs:
  module3_task1_1:


    runs-on: ubuntu-18.04


    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: running setup.sh
        run: |
          cd module3_task2/
          sudo ./setup.sh
      - name: install markdown
        run: npm install -g markdownlint-cli
      - name: help
        run: |
          cd module3_task2
          make help
      - name: build1
        run: |
          cd module3_task2
          make build
      - name: clean
        run: |
          cd module3_task2
          make clean
      - name: build2
        run: |
          cd module3_task2
          make build
      - name: post
        env:
          POST_NAME: name
          POST_TITLE: title
        run: |
          cd module3_task2
          make post
      - name: lint
        run: |
          cd module3_task2
          make lint
      - name: package
        run: |
          cd module3_task2
          make package
